### ISSUE TITLE
Runtimeerr, patch

### ISSUE THREAD

**Issue by parkgyuhwang** [malonge/RagTag#130]
**command line**
`ragtag.py patch -u -t 32 --join-only j_h_read_trimming_gh.bp.p_u.purged.fa polished_contigs.fasta`

**log**
```
Wed Sep 21 10:19:47 2022 --- VERSION: RagTag v2.1.0
Wed Sep 21 10:19:47 2022 --- WARNING: This is a beta version of `ragtag patch`
Wed Sep 21 10:19:47 2022 --- CMD: ragtag.py patch -u -t 32 --join-only j_h_read_trimming_gh.bp.p_u.purged.fa polished_contigs.fasta
Wed Sep 21 10:19:47 2022 --- INFO: Running: ragtag_splitasm.py -o /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.ctg.agp /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/j_h_read_trimming_gh.bp.p_u.purged.fa > /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.ctg.fasta 2> /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.err
Wed Sep 21 10:20:37 2022 --- INFO: Finished running : ragtag_splitasm.py -o /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.ctg.agp /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/j_h_read_trimming_gh.bp.p_u.purged.fa > /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.ctg.fasta 2> /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.err
Wed Sep 21 10:20:37 2022 --- INFO: Running: ragtag_rename.py /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/polished_contigs.fasta -p qseq -o /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.rename.agp > /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.rename.fasta 2> /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.err
Wed Sep 21 10:20:54 2022 --- INFO: Finished running : ragtag_rename.py /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/polished_contigs.fasta -p qseq -o /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.rename.agp > /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.rename.fasta 2> /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.err
Wed Sep 21 10:20:54 2022 --- INFO: Writing: /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.comps.fasta
Wed Sep 21 10:21:29 2022 --- INFO: Mapping the query genome to the target genome
Wed Sep 21 10:21:29 2022 --- INFO: Running: nucmer --maxmatch -l 100 -c 500 -p /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.asm /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.ctg.fasta /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.rename.fasta 2> /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.asm.delta.log
Traceback (most recent call last):
  File "/a/HOME/g/miniconda3/envs/ragtag-env/bin/ragtag_patch.py", line 518, in <module>
    main()
  File "/a/HOME/g/miniconda3/envs/ragtag-env/bin/ragtag_patch.py", line 372, in main
    al.run_aligner()
  File "/a/HOME/g/miniconda3/envs/ragtag-env/lib/python3.7/site-packages/ragtag_utilities/Aligner.py", line 172, in run_aligner
    run_e(self.compile_command(), self.out_log)
  File "/a/HOME/g/miniconda3/envs/ragtag-env/lib/python3.7/site-packages/ragtag_utilities/utilities.py", line 108, in run_e
    raise RuntimeError('Failed : %s 2> %s' % (" ".join(cmd), err))
RuntimeError: Failed : nucmer --maxmatch -l 100 -c 500 -p /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.asm /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.ctg.fasta /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.rename.fasta 2> /a/HOME/g/analysis/047.j_h_a_new/ragtag-j-h-a-nanopore/j_h_read_trimming_gh.bp.p_utg/purged/ragtag_output/ragtag.patch.asm.delta.log

```

**output files**
agtag.patch.asm.delta.log
ragtag.patch.ctg.agp
ragtag.patch.ctg.fasta.fai
ragtag.patch.rename.agp
ragtag.patch.rename.fasta.fai
ragtag.patch.comps.fasta
ragtag.patch.ctg.fasta
ragtag.patch.err
ragtag.patch.rename.fasta

I tried to do with other files, there is same problem.
- python 3.7.12.

**Comment by parkgyuhwang** [comment]
I solved this error as I changed aligner from nucmer to minimap2.
