### ISSUE TITLE
RagTag.py merge

### ISSUE THREAD

**Issue by miangher** [malonge/RagTag#132]
good morning! Two days ago I am using your script to try to improve an assembly of a genome. First of all, I used the flye program (assembly) then Medaka (polish) and after that, from the consensus sequence obtained in Medaka, I used the RagTag program. The correction scaffolding and patching commands did not present any problem. But with Merge I have problems.
According to the instructions:
ragtag.py merge <asm.fa> <scf1.agp> <scf2.agp> [...]
Then:
asm.fa : ragtag.patch.fasta
scf1.agp : ragtag.patch.agp
scf2.agp : ragtag.patch.ctg.agp
scf3.agp : ragtag.patch.rename.agp

ragtag.py merge ragtag.patch.fasta ragtag.patch.agp ragtag.patch.ctg.agp ragtag.patch.rename.agp

Are the order of these entries correct?

I use this command line with the respective entries, but I always get an error:

Fri Sep 23 11:11:26 2022 --- VERSION: RagTag v2.1.0
Fri Sep 23 11:11:26 2022 --- WARNING: This is a beta version of `ragtag merge`
Fri Sep 23 11:11:26 2022 --- CMD: ragtag.py merge ragtag.patch.fasta ragtag.patch.agp ragtag.patch.ctg.agp ragtag.patch.rename.agp
Fri Sep 23 11:11:26 2022 --- WARNING: Without '-u' invoked, some component/object AGP pairs might share the same ID. Some external programs/databases don't like this. To ensure valid AGP format, use '-u'.
Fri Sep 23 11:11:26 2022 --- INFO: Building the scaffold graph from the AGP files
Traceback (most recent call last):
  File "/home/sequenceur/miniconda3/bin/ragtag_merge.py", line 430, in <module>
    main()
  File "/home/sequenceur/miniconda3/bin/ragtag_merge.py", line 362, in main
    agp_multi_sg.add_agps(agp_list, in_weights=weight_list, exclusion_set=comp_exclusion_set)
  File "/home/sequenceur/miniconda3/lib/python3.9/site-packages/ragtag_utilities/ScaffoldGraph.py", line 606, in add_agps
    for ap in self._get_assembly_points(agp, weight):
  File "/home/sequenceur/miniconda3/lib/python3.9/site-packages/ragtag_utilities/ScaffoldGraph.py", line 513, in _get_assembly_points
    raise RuntimeError("{} is in {} but not {}.".format(agp_line.comp, agp, self.components_fasta_fname))
RuntimeError: seq00000005 is in /home/sequenceur/genome_assembly/Lguyanensis_filtree/RagTag/patch/ragtag_output/ragtag.patch.agp but not ragtag.patch.fasta.

Please, could you help me with this problem?
Thank you

**Comment by KunyangWang** [comment]
Hi, I also encountered this problem. Have you finished handling this problem?

**Comment by awesomedeer** [comment]
Same error...

**Comment by dtusso2020** [comment]
Same
