### ISSUE TITLE
Error in patch command

### ISSUE THREAD

**Issue by akhtarmzn2010** [malonge/RagTag#139]
Hi Sir,

I got the same error after run both patch command (A & B): please suggest how i can solve the problem.

A. ragtag.py patch scaffold_RE2/ragtag.scaffold.fasta /media/d/D1/GBS_analysis/NGSEP/reference/AABB_BrapaZ1_BnI100/AABB_BrapaZ1_BnI100.fasta 
B. ragtag.py patch scaffold_RE2/ragtag.scaffold.fasta reference/AABB_BrapaZ1_BnI100.fasta --aligner nucmer -o ragtag_output2 --debug -d 200000

[E::fai_retrieve] Failed to retrieve block: unexpected end of file
Traceback (most recent call last):
  File "/home/d/anaconda3/bin/ragtag_rename.py", line 70, in <module>
    main()
  File "/home/d/anaconda3/bin/ragtag_rename.py", line 61, in main
    print(fai.fetch(reference))
  File "pysam/libcfaidx.pyx", line 319, in pysam.libcfaidx.FastaFile.fetch
ValueError: failure when retrieving sequence on 'B8'

**Comment by adriludwig** [comment]
Hi! I'm wondering if you find and remember what the problem was. I'm getting the same message. Thanks
