### ISSUE TITLE
about paf2delta

### ISSUE THREAD

**Issue by 1085268616** [malonge/RagTag#144]
Could you help me? I don't know how to solve it.

ragtag.py paf2delta /home/zhangzeyu/ragtag_output/jy_ragtag.scaffold.asm.paf
Traceback (most recent call last):
  File "/home/zhangzeyu/anaconda3/bin/ragtag_paf2delta.py", line 183, in <module>
    paf2delta()
  File "/home/zhangzeyu/anaconda3/bin/ragtag_paf2delta.py", line 156, in paf2delta
    raise ValueError("PAF file must contain a CIGAR string. Use 'minimap2 -c'")
ValueError: PAF file must contain a CIGAR string. Use 'minimap2 -c'

**Comment by 1085268616** [comment]
And I use : ragtag.py scaffold RSA_r1.0 jy.output.fasta
I only got three files: jy_ragtag.scaffold.asm.paf  jy_ragtag.scaffold.err  jy_ragtag.scaffold.asm.paf.log.
Is this normal?
