### ISSUE TITLE
Scaffolding error: 'RuntimeError: There are no useful alignments. Check output alignment files.`

### ISSUE THREAD

**Issue by bahiyahazli** [malonge/RagTag#145]
Hello.

I encountered some problems when trying to scaffold. This is my script:

`ragtag.py scaffold -w -u --debug -t 32 ~/wgs-bahiyah/pre/contig-bwa/ref/KT862811.fasta ~/wgs-bahiyah/pre/scaffold-ragtag/ragtag.correct.fasta -o ~/wgs-bahiyah/pre/scaffold-ragtag/`

Below are my python and related dependencies info:
Python3
Unimap, minimap2 and nucmer function well
mummer==3.23
numpy==1.24.0
intervaltree==3.10.0
networkx==2.8.8

And here is my output:

`Sat Dec 24 12:50:03 2022 --- VERSION: RagTag v2.1.0
Sat Dec 24 12:50:03 2022 --- CMD: ragtag.py scaffold -w -u --debug -t 32 /home/bahiyah/wgs-bahiyah/pre/contig-bwa/ref/KT862811.fasta /home/bahiyah/wgs-bahiyah/pre/scaffold-ragtag/ragtag.correct.fasta -o /home/bahiyah/wgs-bahiyah/pre/scaffold-ragtag/
Sat Dec 24 12:50:03 2022 --- INFO: Mapping the query genome to the reference genome
Sat Dec 24 12:50:03 2022 --- INFO: Overwriting pre-existing file: /home/bahiyah/wgs-bahiyah/pre/scaffold-ragtag/ragtag.scaffold.asm.paf
Sat Dec 24 12:50:03 2022 --- INFO: Running: minimap2 -x asm5 -t 32 /home/bahiyah/wgs-bahiyah/pre/contig-bwa/ref/KT862811.fasta /home/bahiyah/wgs-bahiyah/pre/scaffold-ragtag/ragtag.correct.fasta > /home/bahiyah/wgs-bahiyah/pre/scaffold-ragtag/ragtag.scaffold.asm.paf 2> /home/bahiyah/wgs-bahiyah/pre/scaffold-ragtag/ragtag.scaffold.asm.paf.log
Sat Dec 24 12:50:03 2022 --- INFO: Finished running : minimap2 -x asm5 -t 32 /home/bahiyah/wgs-bahiyah/pre/contig-bwa/ref/KT862811.fasta /home/bahiyah/wgs-bahiyah/pre/scaffold-ragtag/ragtag.correct.fasta > /home/bahiyah/wgs-bahiyah/pre/scaffold-ragtag/ragtag.scaffold.asm.paf 2> /home/bahiyah/wgs-bahiyah/pre/scaffold-ragtag/ragtag.scaffold.asm.paf.log
Sat Dec 24 12:50:03 2022 --- INFO: Reading whole genome alignments
Sat Dec 24 12:50:03 2022 --- INFO: Filtering and merging alignments
Traceback (most recent call last):
  File "/home/bahiyah/miniconda3/envs/bioinfo/bin/ragtag_scaffold.py", line 4, in <module>
    __import__('pkg_resources').run_script('RagTag==2.1.0', 'ragtag_scaffold.py')
  File "/home/bahiyah/miniconda3/envs/bioinfo/lib/python3.8/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bahiyah/miniconda3/envs/bioinfo/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1479, in run_script
    exec(script_code, namespace, namespace)
  File "/home/bahiyah/miniconda3/envs/bioinfo/lib/python3.8/site-packages/RagTag-2.1.0-py3.8.egg/EGG-INFO/scripts/ragtag_scaffold.py", line 577, in <module>
  File "/home/bahiyah/miniconda3/envs/bioinfo/lib/python3.8/site-packages/RagTag-2.1.0-py3.8.egg/EGG-INFO/scripts/ragtag_scaffold.py", line 488, in main
RuntimeError: There are no useful alignments. Check output alignment files.`

Do you mind checking where's the hiccup is? I've re-git clone, re-pip install and even re-python3 setup.py install, few times already.
Additionally, I've tried to ./run_run_tests.sh in the /tests/integration_tests/ folder and the test gives out error as well. Probably because of this same issue. 

Thank you so much. Will dig more onto what's actually happening.

**Comment by EmilieSmeets22** [comment]
Hey @bahiyahazli 
Did you figure out the issue?
I just got the exact same error.

Thanks already

**Comment by Sameer1028** [comment]
I am facing the same problem. Can someone please provide their insights?

**Comment by malonge** [comment]
This is not an error with RagTag. It's just saying that there were no alignments that it could use to inform scaffolding. To debug, please analyze the alignment files themselves. And, as you have done, I do recommend using `--debug` so that you can check out the intermediate alignment files as well.
