### ISSUE TITLE
Error message when running ragtag_scaffold.py

### ISSUE THREAD

**Issue by Surbhigrewal** [malonge/RagTag#146]
Hi,

Im running scaffold with ragtag but I am getting the following error

Traceback (most recent call last):
  File "/gpfs01/home/sbzsm11/miniconda3/envs/ragtag/bin/ragtag_scaffold.py", line 577, in <module>
    main()
  File "/gpfs01/home/sbzsm11/miniconda3/envs/ragtag/bin/ragtag_scaffold.py", line 420, in main
    al.run_aligner()
  File "/gpfs01/home/sbzsm11/miniconda3/envs/ragtag/lib/python3.5/site-packages/ragtag_utilities/Aligner.py", line 128, in run_aligner
    run_oe(self.compile_command(), self.out_file, self.out_log)
  File "/gpfs01/home/sbzsm11/miniconda3/envs/ragtag/lib/python3.5/site-packages/ragtag_utilities/utilities.py", line 73, in run_oe
    raise RuntimeError("Failed : %s > %s 2> %s" % (" ".join(cmd), out, err))
RuntimeError: Failed : minimap2 -x asm5 -t 32 ...

Its a very similar message to [issue 17](https://github.com/malonge/RagTag/issues/17) but that was resolved in a version update. However, I'm experiencing this in version 2.1.0. Any help would be appreciated.

**Comment by matthew-pumc** [comment]
This problem might relate to minimap2 out of memory error, you can retry scaffolding with more memory.
