### ISSUE TITLE
Patch error: "Tuple Index out of Range"

### ISSUE THREAD

**Issue by schmigle** [malonge/RagTag#152]
I'm trying to correct a long-read assembly with a short-read scaffold; I'm hoping to fill in the short gaps in the scaffold with the matching long-read sections. The RagTag "patch" function, if I understand correctly, is supposed to do exactly this. Running the Conda version in a Conda environment with Python 3.8.2., I use the following command:

`ragtag.py patch liberibacter_central_ragtag.fasta liberibacter_central_assembly.fasta`

But when I attempt to run it I get the following error:

```
Traceback (most recent call last):
File "/home/u30/moshesteyn/.conda/envs/py382/bin/ragtag_patch.py", line 518, in <module>
    main()
File "/home/u30/moshesteyn/.conda/envs/py382/bin/ragtag_patch.py", line 497, in main
    match_psg = aln_psg.max_weight_matching()
File "/home/u30/moshesteyn/.conda/envs/py382/lib/python3.8/site-packages/ragtag_utilities/ScaffoldGraph.py", line 824, in max_weight_matching
    for cc in nx.connected_components(G=cover_graph):
File "/home/u30/moshesteyn/.conda/envs/py382/lib/python3.8/site-packages/networkx/classes/backends.py", line 134, in wrapper
    graph = args[0]
IndexError: tuple index out of range
```
I've tried running with different files as reference or query, including running with a file of unordered contigs as my query. I've also tried running this with the --fill-only option. All yield the same error. Scaffolding works totally fine. Any ideas?

**Comment by johnsonj161** [comment]
I am also experiencing this issue.

**Comment by ynanyam** [comment]
We found installing older version of `networkx` package resolved this issue. 

```
pip install networkx==2.6.1
```
or 
```
conda install networkx==2.6.1
```
