### ISSUE TITLE
ERROR: encountered an invalid zero or negative numeric AGP field.

### ISSUE THREAD

**Issue by wshuai294** [malonge/RagTag#176]
Thanks for the amazing tool. I met this error whiling scaffolding, could you help me with this?
Here is the log:
```
Fri Jan 19 21:07:55 2024 --- VERSION: RagTag v2.1.0
Fri Jan 19 21:07:55 2024 --- CMD: ragtag.py scaffold -o segment_result//ragtag_DRR198803 /mnt/d/breakpoints/assembly/sim/database/Escherichia_coli/NZ_CP028685.1.fasta segment_result//DRR198803.split.fasta
Fri Jan 19 21:07:55 2024 --- WARNING: Without '-u' invoked, some component/object AGP pairs might share the same ID. Some external programs/databases don't like this. To ensure valid AGP format, use '-u'.
Fri Jan 19 21:07:55 2024 --- INFO: Mapping the query genome to the reference genome
Fri Jan 19 21:07:55 2024 --- INFO: Retaining pre-existing file: /home/wangshuai/assembly_result_v2/segment_result/ragtag_DRR198803/ragtag.scaffold.asm.paf
Fri Jan 19 21:07:55 2024 --- INFO: Reading whole genome alignments
Fri Jan 19 21:07:55 2024 --- INFO: Filtering and merging alignments
Fri Jan 19 21:07:55 2024 --- INFO: Ordering and orienting query sequences
Fri Jan 19 21:07:55 2024 --- INFO: Writing scaffolds
Fri Jan 19 21:07:55 2024 --- INFO: Writing: /home/wangshuai/assembly_result_v2/segment_result/ragtag_DRR198803/ragtag.scaffold.agp
Traceback (most recent call last):
  File "/home/wangshuai/assembly_result/my_assembly/bin/ragtag_scaffold.py", line 577, in <module>
    main()
  File "/home/wangshuai/assembly_result/my_assembly/bin/ragtag_scaffold.py", line 555, in main
    write_orderings(output_path + file_prefix + ".agp", output_path + file_prefix + ".confidence.txt", query_file, mapped_ref_seqs, fltrd_ctg_alns, pad_sizes, gap_types, make_chr0, True, not remove_suffix, skip_no_cat)
  File "/home/wangshuai/assembly_result/my_assembly/bin/ragtag_scaffold.py", line 211, in write_orderings
    agp.add_seq_line(*out_agp_line)
  File "/home/wangshuai/assembly_result/my_assembly/lib/python3.6/site-packages/ragtag_utilities/AGPFile.py", line 215, in add_seq_line
    agp_line = AGPSeqLine(self.fname, line_number, obj, obj_beg, obj_end, pid, comp_type, comp, comp_beg, comp_end, orientation)
  File "/home/wangshuai/assembly_result/my_assembly/lib/python3.6/site-packages/ragtag_utilities/AGPFile.py", line 412, in __init__
    super(AGPSeqLine, self).__init__(fname, line_number, obj, obj_beg, obj_end, pid, comp_type)
  File "/home/wangshuai/assembly_result/my_assembly/lib/python3.6/site-packages/ragtag_utilities/AGPFile.py", line 361, in __init__
    self._validate_numerics()
  File "/home/wangshuai/assembly_result/my_assembly/lib/python3.6/site-packages/ragtag_utilities/AGPFile.py", line 449, in _validate_numerics
    raise AGPError(self.fname, self.line_number, "encountered an invalid zero or negative numeric AGP field.")
ragtag_utilities.AGPFile.AGPError:

FILE : /home/wangshuai/assembly_result_v2/segment_result/ragtag_DRR198803/ragtag.scaffold.agp
LINE : 207
ERROR: encountered an invalid zero or negative numeric AGP field.
```

**Comment by wshuai294** [comment]
solved after removing the existing output files.
