### ISSUE TITLE
ValueError in get_median_read_coverage

### ISSUE THREAD

**Issue by fanzhen199156** [malonge/RagTag#18]
Hi Micheal,
I ran into this error message when running ragtag correct. I supplied with CCS reads with -R option.
Below is the log file.
Date              = Fri Aug 14 15:33:22 EDT 2020
Hostname          = c6a-s20
Working Directory = /blue/whitaker/fanzhen/hifi_test/RTag

```
Number of Nodes Allocated      = 1
Number of Tasks Allocated      = 1
Number of Cores/Task Allocated = 16
Fri Aug 14 15:33:26 2020 --- RagTag v1.0.0
Fri Aug 14 15:33:26 2020 --- CMD: /apps/ragtag/1.0.0/bin/ragtag_correct.py ../ragoo/F_ana_Camarosa_6-28-17_hardmasked.fasta ../ragoo/royal.asm.p_ctg.fa -R SRR11606867.fastq -T corr
Fri Aug 14 15:33:26 2020 --- WARNING: Without '-u' invoked, some component/object AGP pairs might share the same ID. Some external programs/databases don't like this. To ensure valid AGP format, use '-u'.
Fri Aug 14 15:33:26 2020 --- Mapping the query genome to the reference genome
Fri Aug 14 15:33:26 2020 --- Running: minimap2 -x asm5 -t 1 /blue/whitaker/fanzhen/hifi_test/ragoo/F_ana_Camarosa_6-28-17_hardmasked.fasta /blue/whitaker/fanzhen/hifi_test/ragoo/royal.asm.p_ctg.fa > /blue/whitaker/fanzhen/hifi_test/RTag/ragtag_output/c_query_against_ref.paf 2> /blue/whitaker/fanzhen/hifi_test/RTag/ragtag_output/c_query_against_ref.paf.log
Fri Aug 14 16:05:21 2020 --- Finished running : minimap2 -x asm5 -t 1 /blue/whitaker/fanzhen/hifi_test/ragoo/F_ana_Camarosa_6-28-17_hardmasked.fasta /blue/whitaker/fanzhen/hifi_test/ragoo/royal.asm.p_ctg.fa > /blue/whitaker/fanzhen/hifi_test/RTag/ragtag_output/c_query_against_ref.paf 2> /blue/whitaker/fanzhen/hifi_test/RTag/ragtag_output/c_query_against_ref.paf.log
Fri Aug 14 16:05:21 2020 --- Reading whole genome alignments
Fri Aug 14 16:05:25 2020 --- Filtering and merging alignments
Fri Aug 14 16:05:45 2020 --- Validating putative query breakpoints via read alignment.
Fri Aug 14 16:05:45 2020 --- Aligning reads to query sequences.
Fri Aug 14 16:05:45 2020 --- Running: minimap2 -ax asm5 -t 1 /blue/whitaker/fanzhen/hifi_test/ragoo/royal.asm.p_ctg.fa /blue/whitaker/fanzhen/hifi_test/RTag/SRR11606867.fastq > /blue/whitaker/fanzhen/hifi_test/RTag/ragtag_output/c_reads_against_query.sam 2> /blue/whitaker/fanzhen/hifi_test/RTag/ragtag_output/c_reads_against_query.sam.log
Fri Aug 14 16:06:52 2020 --- Finished running : minimap2 -ax asm5 -t 1 /blue/whitaker/fanzhen/hifi_test/ragoo/royal.asm.p_ctg.fa /blue/whitaker/fanzhen/hifi_test/RTag/SRR11606867.fastq > /blue/whitaker/fanzhen/hifi_test/RTag/ragtag_output/c_reads_against_query.sam 2> /blue/whitaker/fanzhen/hifi_test/RTag/ragtag_output/c_reads_against_query.sam.log
Fri Aug 14 16:06:52 2020 --- Compressing, sorting, and indexing read alignments
Fri Aug 14 16:06:52 2020 --- Indexing read alignments
Fri Aug 14 16:06:53 2020 --- Validating putative query breakpoints
Fri Aug 14 16:06:53 2020 --- Calculating global read coverage
Traceback (most recent call last):
  File "/apps/ragtag/1.0.0/bin/ragtag_correct.py", line 645, in <module>
    main()
  File "/apps/ragtag/1.0.0/bin/ragtag_correct.py", line 610, in main
    ctg_breaks = validate_breaks(ctg_breaks, output_path, num_threads, overwrite_files, val_min_break_end_dist, max_cov, min_cov, window_size=val_window_size, clean_dist=min_break_dist, debug=debug_mode)
  File "/apps/ragtag/1.0.0/bin/ragtag_correct.py", line 168, in validate_breaks
    glob_med = get_median_read_coverage(output_path, num_threads, overwrite_files)
  File "/apps/ragtag/1.0.0/bin/ragtag_correct.py", line 124, in get_median_read_coverage
    raise ValueError()
ValueError
```

Please let me know how to solve the issue.
Thanks,
Zhen

**Comment by malonge** [comment]
Hi there, Zhen,

Yes this is poor error reporting that has already come up in another issue. Sorry about the lack of details. Could you run the following command and share the output.

```
grep "COV"  c_reads_against_query.s.bam.stats
```

**Comment by malonge** [comment]
I also see that `Compressing, sorting, and indexing read alignments` was basically instantaneous. How does the SAM file look? Is it empty or truncated?

**Comment by fanzhen199156** [comment]
Hi Micheal,
Thanks for your prompt reply. I ran the grep "COV" c_reads_against_query.s.bam.stats. Below is the output.
# Coverage distribution. Use `grep ^COV | cut -f 2-` to extract this part.
I browse through the whole c_reads_against_query.s.bam.stats document. It appears every number is 0.
I also attached c_reads_against_query.sam.log file.
[c_reads_against_query.sam.log](https://github.com/malonge/RagTag/files/5078946/c_reads_against_query.sam.log)

Many thanks,

**Comment by malonge** [comment]
Hi there,

So it appears that the alignments failed because the following file wasn't found:

`/blue/whitaker/fanzhen/hifi_test/RTag/SRR11606867.fastq`

First of all, can you confirm that the following was your current working directory:
`/blue/whitaker/fanzhen/hifi_test/RTag/`

And if so, does it contain the following file: `SRR11606867.fastq`?

**Comment by fanzhen199156** [comment]
Hi Micheal,
I see, I provided the wrong file path.
Thanks for your help!
