### ISSUE TITLE
The scaffold command was submitted and the assembled result was not available

### ISSUE THREAD

**Issue by LZY19940813** [malonge/RagTag#180]
I assembled scffolds using the contigs file（about 2Gb）that was reassembled from generation 2 by SOAPdenovo2 tool. My scripting have been running for 2 days and I still only have a result file for "ragtag.scaffold.asm.paf". I don't know what the problem is. So, could you tell me if who have any good suggestions. Thank you!

**Comment by LZY19940813** [comment]
Traceback (most recent call last):
  File "/gss1/home/wangzx02/.conda/envs/ragtag/bin/ragtag.py", line 133, in <module>
    main()
  File "/gss1/home/wangzx02/.conda/envs/ragtag/bin/ragtag.py", line 89, in main
    subprocess.call(subcmd)
  File "/gss1/home/wangzx02/.conda/envs/ragtag/lib/python3.6/subprocess.py", line 289, in call
    return p.wait(timeout=timeout)
  File "/gss1/home/wangzx02/.conda/envs/ragtag/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/gss1/home/wangzx02/.conda/envs/ragtag/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
