### ISSUE TITLE
RagTag error: "OSError: error when opening file"

### ISSUE THREAD

**Issue by ylzou867** [malonge/RagTag#187]
I am running RagTag to scaffold an assembly.
It runs fine, makes the log file and part of the output, but at the last step gives an error:

Traceback (most recent call last):
  File "/home/zyl/miniforge3/bin/ragtag_patch.py", line 518, in <module>
    main()
  File "/home/zyl/miniforge3/bin/ragtag_patch.py", line 353, in main
    ref_fai = pysam.FastaFile(reference_ctg_fn)
  File "pysam/libcfaidx.pyx", line 121, in pysam.libcfaidx.FastaFile.__cinit__
  File "pysam/libcfaidx.pyx", line 181, in pysam.libcfaidx.FastaFile._open
OSError: error when opening file `/home/zyl/ragtag/Mjof/ragtag_output/ragtag.patch.ctg.fasta`

**Comment by xubiy** [comment]
During the correction phase, I encountered an error similar to the one previously discussed. 

Has a resolution been found for this issue?
