### ISSUE TITLE
ragtag_break_query.py error

### ISSUE THREAD

**Issue by JonEilers** [malonge/RagTag#2]
I am getting the below error when running ragtag_correct.py

```bash
Sat Jun 13 18:03:36 2020 --- Running: ragtag_break_query.py /home/jon/Working_Files/RagTag/ragtag_output/ragtag.correction.agp /home/jon/Working_Files/Patanus-Allee/assembly/out_contig.fa > /home/jon/Working_Files/RagTag/ragtag_output/out_contig.corrected.fasta
Traceback (most recent call last):
  File "/home/jon/anaconda3/envs/biotools/bin/ragtag_break_query.py", line 4, in <module>
    __import__('pkg_resources').run_script('RagTag==1.0.0', 'ragtag_break_query.py')
  File "/home/jon/anaconda3/envs/biotools/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jon/anaconda3/envs/biotools/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/ragtag_break_query.py' not found in metadata at '/home/jon/Working_Files/RagTag/RagTag.egg-info'
Traceback (most recent call last):
  File "ragtag_correct.py", line 645, in <module>
    main()
  File "ragtag_correct.py", line 641, in main
    run_o(cmd, output_path + qf_pref + ".corrected.fasta")
  File "/home/jon/Working_Files/RagTag/ragtag_utilities/utilities.py", line 91, in run_o
    raise RuntimeError('Failed : %s > %s' % (" ".join(cmd), out))
RuntimeError: Failed : ragtag_break_query.py /home/jon/Working_Files/RagTag/ragtag_output/ragtag.correction.agp /home/jon/Working_Files/Patanus-Allee/assembly/out_contig.fa > /home/jon/Working_Files/RagTag/ragtag_output/out_contig.corrected.fasta
```

**Comment by malonge** [comment]
hi there,

Could you run the following command and report the error?

```
ragtag_break_query.py /home/jon/Working_Files/RagTag/ragtag_output/ragtag.correction.agp /home/jon/Working_Files/Patanus-Allee/assembly/out_contig.fa > /home/jon/Working_Files/RagTag/ragtag_output/out_contig.corrected.fasta
```

**Comment by JonEilers** [comment]
see below
```bash
 ragtag_break_query.py /home/jon/Working_Files/RagTag/ragtag_output/ragtag.correction.agp /home/jon/Working_Files/Patanus-Allee/assembly/out_contig.fa > /home/jon/Working_Files/RagTag/ragtag_output/out_contig.corrected.fasta
Traceback (most recent call last):
  File "/home/jon/anaconda3/envs/biotools/bin/ragtag_break_query.py", line 4, in <module>
    __import__('pkg_resources').run_script('RagTag==1.0.0', 'ragtag_break_query.py')
  File "/home/jon/anaconda3/envs/biotools/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jon/anaconda3/envs/biotools/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/ragtag_break_query.py' not found in metadata at '/home/jon/Working_Files/RagTag/RagTag.egg-info'
```

**Comment by malonge** [comment]
huh interesting

it looks like it is an installation related error. could you share your command to install ragtag?

**Comment by malonge** [comment]
In case it might be useful, could you also share the ragtag.py command that produced the original error?

**Comment by JonEilers** [comment]
So i initially tried 
```bash
python3 ragtag.py
```
and it would show this
```bash
python3 ragtag.py

RagTag: Reference-guided scaffolding and misassembly correction.
Version: v1.0.0

usage: ragtag.py <command> [options]
    
    commands:
      correct         correct contig misassemblies 
      scaffold        scaffold contigs
      updategff       update gff intervals

    options:
      -c, --citation  
      -v, --version
```
However, when I would try 
```bash
python3 ragtag.py correct
```
not surprising in hindsight, it resulted in 
```bash
Traceback (most recent call last):
  File "/home/jon/anaconda3/envs/biotools/bin/ragtag_correct.py", line 4, in <module>
    __import__('pkg_resources').run_script('RagTag==1.0.0', 'ragtag_correct.py')
  File "/home/jon/anaconda3/envs/biotools/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jon/anaconda3/envs/biotools/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/ragtag_correct.py' not found in metadata at '/home/jon/Working_Files/RagTag/RagTag.egg-info'
```

so I took a peak at the ragtag script and saw it was mostly a wrapper for calling the other scripts so I just jumped to the ragtag_correct.py script. 
```bash
python3 ragtag_correct.py \
 /home/jon/Working_Files/genome_assemblies/Ajap_genome.fasta \
 /home/jon/Working_Files/Patanus-Allee/assembly/out_contig.fa \
 -t 70 \
 -R /home/jon/Working_Files/pcali_raw_data/P_cali_g_1.fq.gz \
 -R /home/jon/Working_Files/pcali_raw_data/P_cali_g_2.fq.gz \
 -T sr 
```
I'll probably just wait until the conda version is out. Is there anything you want me to check for figuring out why the scripts weren't added to my path though?

**Comment by malonge** [comment]
Thanks - got it

Yes RagTag does need to be installed first with `python3 setup.py install`. If you don't have root access you can setup a virtualenv.

Once it is installed, it should just be run like this:

`ragtag.py` 

I am going to close this issue for now and I will update the README when it is ready to be installed through conda. Hopefully that will be within the next week or so.

Thanks
