### ISSUE TITLE
Something wrong in the writing agp file

### ISSUE THREAD

**Issue by Zea1nfO** [malonge/RagTag#21]
Hi sir
i meet some error at the writing agp file stage.
here is the log:

Tue Aug 25 09:51:59 2020 --- RagTag v1.0.1
Tue Aug 25 09:51:59 2020 --- CMD: ragtag_scaffold.py chr.fa SY1032.Scf.fasta -o res --aligner /mummer4/bin/nucmer --nucmer-params -l 20 --threads=16 -u
Tue Aug 25 09:51:59 2020 --- Mapping the query genome to the reference genome
Tue Aug 25 09:51:59 2020 --- Retaining pre-existing file: query_against_ref.delta
Tue Aug 25 09:51:59 2020 --- Running: ragtag_delta2paf.py res/query_against_ref.delta > res/query_against_ref.paf
Tue Aug 25 10:13:54 2020 --- Finished running : ragtag_delta2paf.py res/query_against_ref.delta > res/query_against_ref.paf
Tue Aug 25 10:13:54 2020 --- Reading whole genome alignments
Tue Aug 25 10:16:12 2020 --- Filtering and merging alignments
Tue Aug 25 10:18:19 2020 --- Ordering and orienting query sequences
Tue Aug 25 10:18:19 2020 --- Writing scaffolds
Tue Aug 25 10:18:19 2020 --- Writing: res/ragtag.scaffolds.agp
Traceback (most recent call last):
  File "/anaconda3/bin/ragtag_scaffold.py", line 528, in <module>
    main()
  File "/anaconda3/bin/ragtag_scaffold.py", line 506, in main
    write_orderings(output_path + "ragtag.scaffolds.agp", output_path + "ragtag.confidence.txt", query_file, mapped_ref_seqs, fltrd_ctg_alns, pad_sizes, gap_types, make_chr0, overwrite_files, not remove_suffix)
  File "/anaconda3/bin/ragtag_scaffold.py", line 192, in write_orderings
    agp.add_seq_line(*out_agp_line)
  File "/anaconda3/lib/python3.7/site-packages/ragtag_utilities/AGPFile.py", line 170, in add_seq_line
    self._raise_line_err(line_number, "object identifier out of order")
  File /anaconda3/lib/python3.7/site-packages/ragtag_utilities/AGPFile.py", line 71, in _raise_line_err
    raise ValueError(message)
ValueError: line 133: object identifier out of order

Do you have any idea to solve this?
Thanks a lot.

**Comment by Zea1nfO** [comment]
It seems that my delta file is too big.
And then i change some parameter to shrink it to be on Mb level (previous was on a Gb level), the ragtag is running fine.
