### ISSUE TITLE
Unable to get corrected fasta and AGP file after using Pacbio reads

### ISSUE THREAD

**Issue by bhidek** [malonge/RagTag#34]
Hello,

I generated assembly with Illumina reads (both paired end and mate pairs) and Pacbio long reads. 
I was able to correct and validate query assembly using Illumina reads (using -T sr option in RagTag).

I wanted to use Pacbio reads for correction as well. 
Hence used corrected assembly based on Illumina reads as input and used -T corr option. 
This generated SAM, BAM file and BAM stats file and log files without any errors. 

**In BAM stats file, it has listed 248 reads mapped as well.**

Still I get following error and it fails to generate AGP file and corrected fasta file
Traceback (most recent call last):
  File "RagTag-1.0.1/bin/ragtag_correct.py", line 4, in <module>
    __import__('pkg_resources').run_script('RagTag==1.0.1', 'ragtag_correct.py')
  File "Python-3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "Python-3.6.5/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "RagTag-1.0.1/lib/python/RagTag-1.0.1-py3.6.egg/EGG-INFO/scripts/ragtag_correct.py", line 645, in <module>
  File "RagTag-1.0.1/lib/python/RagTag-1.0.1-py3.6.egg/EGG-INFO/scripts/ragtag_correct.py", line 608, in main
  File "RagTag-1.0.1/lib/python/RagTag-1.0.1-py3.6.egg/EGG-INFO/scripts/ragtag_correct.py", line 168, in validate_breaks
  File "RagTag-1.0.1/lib/python/RagTag-1.0.1-py3.6.egg/EGG-INFO/scripts/ragtag_correct.py", line 124, in get_median_read_coverage
**ValueError: Unable to calculate read coverage. Check SAM/BAM files and stats file.**

Any help in this regard will be really helpful.

Regards
Ketaki

**Comment by malonge** [comment]
Hi there,

Sorry about the late reply. Can you run the following command and share the output?

`grep ^"COV" c_reads_against_query.s.bam.stats`
