### ISSUE TITLE
Syntax error " yield from walk(new_path, topdown, onerror, followlinks)"

### ISSUE THREAD

**Issue by atiaamin2019** [malonge/RagTag#70]
I am getting the following syntax error when trying to install. Any idea how to resolve it? 
```
conda install -c bioconda ragtag
Traceback (most recent call last):
  File "/cvmfs/soft.mugqic/CentOS6/software/python/Python-3.6.5/lib/python3.6/site-packages/site.py", line 73, in <module>
    __boot()
  File "/cvmfs/soft.mugqic/CentOS6/software/python/Python-3.6.5/lib/python3.6/site-packages/site.py", line 3, in __boot
    import os
  File "/cvmfs/soft.mugqic/CentOS6/software/python/Python-3.6.5/lib/python3.6/os.py", line 409
    yield from walk(new_path, topdown, onerror, followlinks)
             ^
SyntaxError: invalid syntax

```

**Comment by malonge** [comment]
Just a guess but it looks like your python interpreters are mixed up. Perhaps you could try making a dedicated conda environment (Python3).

**Comment by atiaamin2019** [comment]
Thanks for your reply. Yes, the issue was related to the Python version I was using. Solved it.
