### ISSUE TITLE
ResolutionError: Script 'scripts/ragtag.py' not found in metadata

### ISSUE THREAD

**Issue by mavino** [malonge/RagTag#83]
I am running the command
```
 python3 ragtag_scaffold.py /home/mariano/Documents/Wellinger/GCA_002057635.1_ASM205763v1_genomic.fna /home/mariano/Documents/Wellinger/GCA_000773925.1_ASM77392v1_genomic.fna-1 --aligner /home/mariano/Downloads/minimap2/minimap2
```
and I get this error in the file ragtag.scaffold.err:
```
Traceback (most recent call last):
  File "/home/mariano/miniconda3/bin/ragtag_agp2fa.py", line 4, in <module>
    __import__('pkg_resources').run_script('RagTag==2.0.1', 'ragtag_agp2fa.py')
  File "/home/mariano/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mariano/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/ragtag_agp2fa.py' not found in metadata at '/home/mariano/miniconda3/lib/python3.8/site-packages/RagTag-2.0.1.dist-info'
```

**Comment by malonge** [comment]
Hi there,

That is not the correct usage. Please see the Wiki for the correct [installation](https://github.com/malonge/RagTag/wiki/Installation) and [usage](https://github.com/malonge/RagTag/wiki/Usage).

**Comment by mavino** [comment]
OK I see...this is what I have done so far::
first I installed it this way having the following problem
```
conda install -c bioconda ragtag
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - feature:|@/linux-64::__glibc==2.27=0

Your installed version is: 2.27
```

Then reading similar issue on your github page I tried:

```
pip install RagTag
Collecting RagTag
  Downloading RagTag-2.0.1-py3-none-any.whl (84 kB)
     |████████████████████████████████| 84 kB 2.8 MB/s 
Requirement already satisfied: numpy in ./miniconda3/lib/python3.8/site-packages (from RagTag) (1.19.4)
Collecting intervaltree
  Downloading intervaltree-3.1.0.tar.gz (32 kB)
Requirement already satisfied: pysam in ./miniconda3/lib/python3.8/site-packages (from RagTag) (0.16.0.1)
Collecting networkx
  Downloading networkx-2.6.3-py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 12.2 MB/s 
Collecting sortedcontainers<3.0,>=2.0
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Building wheels for collected packages: intervaltree
  Building wheel for intervaltree (setup.py) ... done
  Created wheel for intervaltree: filename=intervaltree-3.1.0-py2.py3-none-any.whl size=26100 sha256=23491a774a063eedb89534aa33a5f9763faf69669ebf7dca2d30821b46e5790c
  Stored in directory: /home/mariano/.cache/pip/wheels/45/23/de/5789a92962483fd33cb06674792b9697c1b3766d7c7742830e
Successfully built intervaltree
Installing collected packages: sortedcontainers, intervaltree, networkx, RagTag
Successfully installed RagTag-2.0.1 intervaltree-3.1.0 networkx-2.6.3 sortedcontainers-2.4.0
```

Then I got confused on how to start it, so I also install it through git clone and python3 setup.py install having successfull installation.

However every time that I tried to open it I get this error:

```
ragtag.py
Traceback (most recent call last):
  File "/home/mariano/miniconda3/bin/ragtag.py", line 4, in <module>
    __import__('pkg_resources').run_script('RagTag==2.0.1', 'ragtag.py')
  File "/home/mariano/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mariano/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/ragtag.py' not found in metadata at '/home/mariano/miniconda3/lib/python3.8/site-packages/RagTag-2.0.1.dist-info'

Would you please tell me now if I am doing anything wrong?
Thank you so much

**Comment by malonge** [comment]
Hmm assuming you are using python3, I can't think of any reason why this wouldn't work. I suppose another option is to try conda again but using a conda environment.

**Comment by mavino** [comment]
yes python 3...
OK I tried to use conda environment and this where I am now:
```
conda create -n ragtag python=3.8.3 anaconda
source activate ragtag
conda install -n ragtag ragtag
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - ragtag

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by mavino** [comment]
Searching for "failed with initial frozen solve. Retrying with flexible solv" which I always get when I use conda I came across https://stackoverflow.com/questions/57518050/conda-install-and-update-do-not-work-also-solving-environment-get-errors and I used some of their solutions:
```
conda update --all --yes
```
After that I retried:
```
conda install -c bioconda ragtag
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                      

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - python=3.8 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.27
```

**Comment by mavino** [comment]
It looks I fixed the problem with the following
```
conda create -n ragtag python=3.7.3
conda activate ragtag
conda install -c bioconda ragtag
ragtag.py

RagTag: Tools for fast and flexible genome assembly scaffolding and improvement.
Version: v2.0.1

usage: ragtag.py <command> [options]
    
    assembly improvement:
      correct         homology-based misassembly correction
      scaffold        homology-based assembly scaffolding
      patch           homology-based assembly patching
      merge           scaffold merging
      
    file utilities:
      agp2fa          build a FASTA file from an AGP file
      agpcheck        check for valid AGP file format
      asmstats        assembly statistics
      splitasm        split an assembly at gaps
      delta2paf       delta to PAF file conversion
      paf2delta       PAF to delta file conversion
      updategff       update gff intervals
      

    options:
      -c, --citation  
      -v, --version
```
