### ISSUE TITLE
merge problems

### ISSUE THREAD

**Issue by yuzhenpeng** [malonge/RagTag#89]
Hello, I got a warning shown as follow, could you give me some suggestion.
Thanks.
```
$ragtag.py merge -b ../../SALSA/combined.bam guatoujing.contig.purged.fa ./out2/ragtag.scaffold.agp ./out3/ragtag.scaffold.agp other.map.agp -o scaffold
Mon Nov 29 18:57:50 2021 --- VERSION: RagTag v2.1.0
Mon Nov 29 18:57:50 2021 --- WARNING: This is a beta version of `ragtag merge`
Mon Nov 29 18:57:50 2021 --- CMD: ragtag.py merge -b ../../SALSA/combined.bam guatoujing.contig.purged.fa ./out2/ragtag.scaffold.agp ./out3/ragtag.scaffold.agp other.map.agp -o scaffold
Mon Nov 29 18:57:50 2021 --- WARNING: Without '-u' invoked, some component/object AGP pairs might share the same ID. Some external programs/databases don't like this. To ensure valid AGP format, use '-u'.
Mon Nov 29 18:57:50 2021 --- INFO: Building the scaffold graph from the AGP files
Traceback (most recent call last):
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/liftoff/bin/ragtag_merge.py", line 430, in <module>
    main()
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/liftoff/bin/ragtag_merge.py", line 362, in main
    agp_multi_sg.add_agps(agp_list, in_weights=weight_list, exclusion_set=comp_exclusion_set)
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/liftoff/lib/python3.6/site-packages/ragtag_utilities/ScaffoldGraph.py", line 606, in add_agps
    for ap in self._get_assembly_points(agp, weight):
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/liftoff/lib/python3.6/site-packages/ragtag_utilities/ScaffoldGraph.py", line 578, in _get_assembly_points
    raise ValueError("Input AGPs do not have the same set of components.")
ValueError: Input AGPs do not have the same set of components.
```

![image](https://user-images.githubusercontent.com/31943277/144017298-70ba5864-b782-4e12-8812-23d06e9e8ac7.png)

**Comment by yuzhenpeng** [comment]
I can not understand. Would you mind give more help?

**Comment by malonge** [comment]
It appears that you are also using a file called `other.map.agp`. Is this also from RagTag?

**Comment by yuzhenpeng** [comment]
thank you. Got it

**Comment by 14zac2** [comment]
Hello! I also had this issue - I think the way you have written the Github README is a bit confusing, as it is not entirely clear that `other.map.agp` is a standin for other AGP files the user may have.
