### ISSUE TITLE
Inconsistent mapping to reference results (minimap2)

### ISSUE THREAD

**Issue by fredericgaspar** [malonge/RagTag#92]
Hi!
When I use minimap2 in Geneious (minimap2_macos -x map-ont --frag=yes --secondary=no -a ref.fasta query.fasta -o output.sam) or with the command line (minimap2 -x map-ont --frag=yes --secondary=no -a ref.fasta query.fasta -o output.sam), all my contigs (167) map to my reference genome.
When I use RagTag with minimap2 only 155 map to the reference (ragtag.py scaffold -r -g 1 -f 500 --aligner /home/ubuntu/miniconda3/envs/ragtag/bin/minimap2 --mm2-params '-x map-ont' ref.fasta query.fasta).
Any (obvious) reason for the difference? 
Thank you for your help!

**Comment by malonge** [comment]
Hi there,

It looks like you are using different parameters. You can try the following:

```
ragtag.py scaffold -r -g 1 -f 500 --aligner /home/ubuntu/miniconda3/envs/ragtag/bin/minimap2 --mm2-params '-x map-ont --frag=yes --secondary=no' ref.fasta query.fasta
```

**Comment by fredericgaspar** [comment]
That was fast!
🤩

I tried that option previously ('-x map-ont --frag=yes --secondary=no') but I got an error message (below), hence the shift to '-x map-ont'.

Thu Dec 30 00:31:55 2021 --- VERSION: RagTag v2.1.0
Thu Dec 30 00:31:55 2021 --- CMD: ragtag.py scaffold -r -g 1 -f 500 --aligner /home/ubuntu/miniconda3/envs/ragtag/bin/minimap2 --mm2-params -x map-ont --frag=yes --secondary=no ref.fasta query.fasta
Thu Dec 30 00:31:55 2021 --- WARNING: Without '-u' invoked, some component/object AGP pairs might share the same ID. Some external programs/databases don't like this. To ensure valid AGP format, use '-u'.
Thu Dec 30 00:31:55 2021 --- INFO: Mapping the query genome to the reference genome
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/ragtag/bin/ragtag_scaffold.py", line 577, in <module>
    main()
  File "/home/ubuntu/miniconda3/envs/ragtag/bin/ragtag_scaffold.py", line 420, in main
    al.run_aligner()
  File "/home/ubuntu/miniconda3/envs/ragtag/lib/python3.7/site-packages/ragtag_utilities/Aligner.py", line 126, in run_aligner
    if all([self.params_are_valid(), self.exec_is_valid()]):
  File "/home/ubuntu/miniconda3/envs/ragtag/lib/python3.7/site-packages/ragtag_utilities/Aligner.py", line 199, in params_are_valid
    raise ValueError("Alignments must not be in SAM format (-a).")
ValueError: Alignments must not be in SAM format (-a).

😓

**Comment by malonge** [comment]
Ah ok you have identified a bug in the way RagTag parses the aligner parameters. It currently cannot handle double hyphen command line parameters, such as `--frag=yes`. I will fix this and included in the next release.

In the meantime, I would just run minimap2 externally and plug it in manually, as described one #86 

Sorry about that!

**Comment by malonge** [comment]
Specifically, I think it would fail using any double hyphen parameter with an "a" or "c" character in it since those trigger a warning.

**Comment by fredericgaspar** [comment]
Thank you for taking the time to look at this…
☺️

I performed the alignment in minimap2 externally with an output as *.paf

minimap2 -x map-ont --frag=yes --secondary=no ref.fasta query.fasta > ragtag.scaffold.asm.paf

Created the folder ragtag_output and moved the ragtag.scaffold.asm.paf file inside

Performed:

ragtag.py scaffold -r -u -g 1 -f 500 ref.fasta query.fasta

Everything went fine with no bug/crash.

But the problem remains the same as initially…

Minimap2 correctly maps 167/167 contigs to the reference, but RagTag only uses 155 of those mapped contigs for the scaffold (not using the res / no contigs were smaller than 500).

**Comment by malonge** [comment]
I suggest running ragtag with `--debug`, which will output a `ragtag.scaffold.debug.merged.paf` file. These are the alignments actually used for scaffolding after filtering/merging. Check how many of the contigs have alignments in this file and that should tell us what is going on. I suspect that the alignments for these missing contigs just got filtered out by RagTag.

**Comment by fredericgaspar** [comment]
I just looked at the alignments and you are correct! The missing contigs (as seen at the end of the ragtag.scaffold.agp output file, sizes between 511 and 1845) were indeed filtered out by ragtag… 😓

They were in the ragtag.scaffold.asm.paf file (in yellow in the pdf in attachment)… Remained in the ragtag.scaffold.debug.unfiltered.paf…
And are missing in the filtered and merged files…
Also there are 2 contigs with the same name that map to the beginning and end of the chromosome and 1 of them was also filtered out (2 first lines in yellow in the pdf in attachment) (maybe I can’t have 1 sequence broken in 2 sequences with the same name)...

Do I have to play with some filtering/scaffolding options to solve the filtering out or maybe in this case RagTag is not the ideal tool?

**Comment by malonge** [comment]
1) Yes each sequence should have a unique header in the fasta files.

2) There are some parameters that can be tuned for filtering and merging:

```
-f
--remove-small
-q
-d
-i
-a
-s
```

While parameter tuning is sometimes warranted, alignments are generally filtered out for a good reason. If you are very confident that these alignments should remain because they represent unambigous matches to the reference, then you can try to tune parameters or even use a different aligner. But it may also just be the case that the contigs are not long enough to be confidently placed by any homology-based scaffolding software via any whole-genome aligner. Its better to leave a contig unplaced than to inaccurately place it.

**Comment by fredericgaspar** [comment]
Thank you so much (again) for taking the time to provide all these clarifications... In my specific case I do need to use all contigs for statistics purposes...
However, I do see your point and for sure I will use RagTag in the future! 🤓👍🏼
(Happy New Year!)

**Comment by malonge** [comment]
Thanks and happy new year! Let's keep this open until I fix this bug.
