### ISSUE TITLE
Error in merge with Hi-C data

### ISSUE THREAD

**Issue by Shokusei** [malonge/RagTag#99]
Hello, @malonge 
I tried to merge my 3 scaffolds obtained by command "ragtag.py scaffold" using corrected fasta.
Bam file of the hic was attached with the index.
And, that command was below.

ragtag.py merge ../correct/correct_At_Mc/ragtag.correct.fasta ../scaffold/scaffold_AT2/ragtag.scaffold.agp ../scaffold/scaffold_JC3/ragtag.scaffold.agp ../scaffold/scaffold_EU2/ragtag.scaffold.agp -b ../../Hi-C/Hi-C.bam -l 100000 -o merge_JC_EU_AT_220121 -u

please tell me which was wrong, and what command can solve this problem.
Thank you.

(base) [iceplant4561@gw1 merge_JC_EU_AT_220121]$ cat ragtag.merge.err
Fri Jan 21 09:41:03 2022 --- INFO: Computing raw Hi-C links from: /lustre7/home/iceplant4561/WGS/Hi-C/Hi-C.bam
Fri Jan 21 09:44:53 2022 --- INFO: Using the following restriction sites:
    Sau3AI: GATC
Fri Jan 21 09:44:53 2022 --- INFO: Counting restriction sites
Fri Jan 21 09:44:59 2022 --- INFO: Normalizing raw Hi-C links
Traceback (most recent call last):
  File "/home/iceplant4561/anaconda3/envs/Ragtag/bin/ragtag_create_links.py", line 242, in <module>
    main()
  File "/home/iceplant4561/anaconda3/envs/Ragtag/bin/ragtag_create_links.py", line 237, in main
    norm_links = normalize_links(raw_links, l_norm_factors, r_norm_factors)
  File "/home/iceplant4561/anaconda3/envs/Ragtag/bin/ragtag_create_links.py", line 136, in normalize_links
    norm_links[i][j] = raw_links[i][j] / (first_norm + second_norm)
ZeroDivisionError: division by zero
(base) [iceplant4561@gw1 merge_JC_EU_AT_220121]$

**Comment by heziqing** [comment]
Hello Shokusei,
I encountered the same issue. Have you solved the problem?

And my commond and errors were below.
ragtag.py merge -b hic_sorted.bam -r 'GATC' -u i_Rs_contigs.fasta scaffold_h_18Rs_ref.agp scaffold_i_19Rs_ref.agp

Wed Jan 26 00:34:48 2022 --- INFO: Computing raw Hi-C links from: /datb/heziqing/1_R_sinicus/ragtag_merge/hic_align/hic_sorted.bam
Wed Jan 26 01:45:54 2022 --- INFO: Using the following restriction sites:
    Sau3AI: GATC
Wed Jan 26 01:45:54 2022 --- INFO: Counting restriction sites
Wed Jan 26 01:46:22 2022 --- INFO: Normalizing raw Hi-C links
Traceback (most recent call last):
  File "/share/home/heziqing/miniconda3/envs/ragtag/bin/ragtag_create_links.py", line 242, in <module>
    main()
  File "/share/home/heziqing/miniconda3/envs/ragtag/bin/ragtag_create_links.py", line 237, in main
    norm_links = normalize_links(raw_links, l_norm_factors, r_norm_factors)
  File "/share/home/heziqing/miniconda3/envs/ragtag/bin/ragtag_create_links.py", line 136, in normalize_links
    norm_links[i][j] = raw_links[i][j] / (first_norm + second_norm)
ZeroDivisionError: division by zero

**Comment by malonge** [comment]
Hi there,

At a glance, this appears to happen when there are sequences with no restriction fragment sites. I'll leave this issue open as a bug because the software should be able to handle this, but as a temporary fix you can run using "DNase" (which just normalizes by the length of the sequence, not the number of restriction sites). Or you can try to identify the sequences with no sites and remove them. I am guessing that they are too small to scaffold anyways.
